//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task3Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public Information()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Age { get; set; }
        public string Job_Title { get; set; }
        public string Gender { get; set; }
        public string Image { get; set; }
        public string Cv { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}

