//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace athountication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public string CatName { get; set; }
        public string Image { get; set; }
        public string Price { get; set; }
        public int CatID { get; set; }
        public Nullable<int> NewPrice { get; set; }
    }
}
